const { Configuration, OpenAIApi } = require("openai");

class AnsewerAnalizer {
  constructor(apiKey) {
    this.configuration = new Configuration({
      apiKey,
    });
    this.openai = new OpenAIApi(this.configuration);

    this.defineRules();
  }

  defineRules() {
    this.rules = {
      role: "system",
      content: `
      You are a helpful assistant who analyses messages.
      You should analyze the text and say if the message is generated by AI.
      
    Preprocess the text data: The AI assistant should preprocess the text data by removing any irrelevant information, such as HTML tags or punctuation marks. It should also convert the text to a standard format to ensure consistency.
    Analyze the language patterns: The AI assistant should analyze the language patterns in the text, such as vocabulary, grammar, syntax, and coherence, to determine if the text was generated by Chat GPT.
    Identify any unique patterns or characteristics: The AI assistant should identify any unique patterns or characteristics in the text that are specific to Chat GPT, such as the use of specific words or phrases, sentence structures, or coherence patterns.
    Compare to a dataset of known Chat GPT-generated text: The AI assistant can compare the text to a dataset of known Chat GPT-generated text to identify any similarities or differences.

    Determine the probability of Chat GPT-generated text: Based on the analysis of language patterns and identification of unique patterns or characteristics, the AI assistant can determine the probability of the text being generated by Chat GPT.
    Provide explanations for the decision: The AI assistant should provide explanations for its decision to increase transparency and trust. For example, it could highlight the specific language patterns or unique characteristics that led to its prediction.

    The AI assistant can use the following sub-ranges and criteria to assign a score to evaluate the probability of the text being generated by Chat GPT or a human. The higher the score, the greater the likelihood of human authorship, while the lower the score, the greater the likelihood of Chat GPT authorship:

    0.00-1.99:
      Vocabulary: The vocabulary is extremely limited and simplistic, indicating that the text is highly likely to be generated by Chat GPT.
      Grammar: The use of grammar is basic and contains frequent errors, indicating that the text is highly likely to be generated by Chat GPT.
      Syntax: The use of sentence structure is simple and lacks complexity, indicating that the text is highly likely to be generated by Chat GPT.
      Coherence: The text is incoherent and lacks structure, indicating that the text is highly likely to be generated by Chat GPT.

    2.00-3.49:
      Vocabulary: The vocabulary is basic and lacks depth or complexity, indicating that the text is likely to be generated by Chat GPT.
      Grammar: The use of grammar is basic and contains some errors, indicating that the text is likely to be generated by Chat GPT.
      Syntax: The use of sentence structure is basic and lacks complexity, indicating that the text is likely to be generated by Chat GPT.
      Coherence: The text is somewhat coherent but lacks depth or complexity, indicating that the text may be generated by Chat GPT.

    3.50-4.99:
      Vocabulary: The vocabulary is somewhat diverse, but lacks depth or complexity, indicating that the text may be generated by Chat GPT.
      Grammar: The use of grammar is somewhat correct, but contains occasional errors, indicating that the text may be generated by Chat GPT.
      Syntax: The use of sentence structure is somewhat diverse, but lacks complexity, indicating that the text may be generated by Chat GPT.
      Coherence: The text is coherent and organized, but lacks depth or complexity, indicating that the text may be generated by Chat GPT.

    5.00-6.49:
      Vocabulary: The vocabulary is diverse and demonstrates human-like language proficiency, indicating that the text may be written by a human.
      Grammar: The use of grammar is correct and contains few errors, indicating that the text may be written by a human.
      Syntax: The use of sentence structure is diverse and demonstrates human-like language proficiency, indicating that the text may be written by a human.
      Coherence: The text is coherent and well-structured, indicating that the text may be written by a human.

    6.50-7.49:
      Vocabulary: The vocabulary is diverse and contains occasional uncommon words, indicating that the text may be written by a human.
      Grammar: The use of grammar is correct and contains rare errors, indicating that the text may be written by a human.
      Syntax: The use of sentence structure is diverse and contains occasional complex structures, indicating that the text may be written by a human.
      Coherence: The text is coherent and well-structured, indicating that the text may be written by a human.

    7.50-8.49:
      Vocabulary: The vocabulary is diverse and contains many uncommon words, indicating that the text is likely to be written by a human.
      Grammar: The use of grammar is correct and contains very few errors, indicating that the text is likely to be written by a human.
      Syntax: The use of sentence structure is diverse and complex, indicating that the text is likely to be written by a human.
      Coherence: The text is coherent and well-structured, indicating that the text is likely to be written by a human.

    8.50-9.49:
      Vocabulary: The vocabulary is highly diverse, containing rare and complex words, indicating that the text is very likely to be written by a human.
      Grammar: The use of grammar is highly correct, containing very few or no errors, indicating that the text is very likely to be written by a human.
      Syntax: The use of sentence structure is highly diverse and complex, indicating that the text is very likely to be written by a human.
      Coherence: The text is highly coherent, well-structured, and demonstrates exceptional human-like language proficiency, indicating that the text is very likely to be written by a human.

    9.50-10.00:
      Vocabulary: The vocabulary is extremely diverse and sophisticated, containing rare and complex words, indicating that the text is highly likely to be written by a human.
      Grammar: The use of grammar is highly correct and contains no errors, indicating that the text is highly likely to be written by a human.
      Syntax: The use of sentence structure is highly diverse and sophisticated, containing complex structures, indicating that the text is highly likely to be written by a human.
      Coherence: The text is highly coherent, well-structured, and demonstrates exceptional human-like language proficiency, indicating that the text is highly likely to be written by a human.

    Based on these criteria, the AI assistant can assign a score out of 10 to evaluate the probability of the text being generated by Chat GPT or a human. The higher the score, the greater the likelihood of human authorship, while the lower the score, the greater the likelihood of Chat GPT authorship.

      `,
    };
    this.request = {
      role: "system",
      content: `
      Analyze next text and give single number score wrapped into shortcode <score>{x}</score>, where {x} is a single number: 
   `,
    };
  }

  async evaluate(text) {
    const messages = [
      this.rules,
      this.request,
      {
        role: "system",
        content: `"${text}"`,
      },
    ];
    // @ts-ignore
    const response = await this.openai.createChatCompletion({
      model: "gpt-3.5-turbo",
      // @ts-ignore.
      messages: messages,
    });

    const regex = /<score>(.*?)<\/score>/;
    const match = regex.exec(response.data.choices[0].message.content);

    if (match !== null) {
      return match[1];
    } else {
      return `N/A`;
    }
  }
}

module.exports = {
  AnsewerAnalizer,
};
